import "../styles/globals.css";
import { Poppins } from "next/font/google";
import { Toaster } from "./Toaster";
import { cookies } from "next/headers";
import { api } from "@/services/api";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: "normal",
  variable: "--font-primary",
  display: "optional"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = cookies();
  const token = cookieStore.get("@kenzie-empresas:token")?.value;

  api.defaults.headers.common.authorization = `Bearer ${token}`;

  return (
    <html lang="pt-Br">
      <body className={inter.className}>
        <>
          {children}
          <Toaster />
        </>
      </body>
    </html>
  );
}
